#CONSTANTS FOR ABSOLUTE CONTROLLED LISTS
#(Please lists order of constants listed prefaced by 3 #'s below)

###
#TYPE_DIGITAL
#TYPE_CONTENT
#ROLE
#FILE_FORMAT
#GENRE
#LANGUAGE

#NOTE:
#Collections/Archives, Contributing Institutions, and Physical Types are all autocomplete fields.
#
#You can write whatever you want and the autocomplete suggestions are distinct values
#that have been entered in the past related to what you are typing
#
#In short they're not constant so they shouldn't go here.
#
#Probably be queried from DB into a prepared statement on page load like this...
#   SELECT DISTINCT collection FROM archive_entry


#
#
#[type_digital_id TINYINT(255), type_digital VARCHAR(63), description TEXT(1023)]
TYPE_DIGITAL = [
[0,'Digital Image','Description of Digital Image.'],
[1,'Digital Transcription of Text','Description of Digital Transcription of Text'],
]

#
#
#[type_content_id TINYINT(255), type_content VARCHAR(63), description TEXT(1023)]
TYPE_CONTENT = [
[0,'Collection','An aggregation of resources.'],
[1,'Dataset','Data encoded in a defined structure.'],
[2,'Event','A non-persistent, time-based occurrence.'],
[3,'Image','A visual representation other than text.'],
[4,'Interactive Resource','A resource requiring interaction from the user to be understood, executed, or experienced.'],
[5,'Moving Image','A series of visual representations imparting an impression of motion when shown in succession.'],
[6,'Physical Object','An inanimate, three-dimensional object or substance.'],
[7,'Service','A system that provides one or more functions.'],
[8,'Software','A computer program in source or compiled form.'],
[9,'Sound','A resource primarily intended to be heard.'],
[10,'Still Image','A static visual representation.'],
[11,'Text','A resource consisting primarily of words for reading.'],
]

#
#
#[role VARCHAR(3), role_full VARCHAR(63), description TEXT(1023)]
ROLE = [
['abr','Abridger',
'A person, family, or organization contributing to a resource by shortening or condensing the original work but leaving the nature and content of the original work substantially unchanged. For substantial modifications that result in the creation of a new work, see author'],
['act','Actor',
'A performer contributing to an expression of a work by acting as a cast member or player in a musical or dramatic presentation, etc.'],
['adp','Adapter',
'A person or organization who 1) reworks a musical composition, usually for a different medium, or 2) rewrites novels or stories for motion pictures or other audiovisual medium.'],
['rcp','Addressee',
'A person, family, or organization to whom the correspondence in a work is addressed'],
['anl','Analyst',
'A person or organization that reviews, examines and interprets data or information in a specific area'],
['anm','Animator',
'A person contributing to a moving image work or computer program by giving apparent movement to inanimate objects or drawings. For the creator of the drawings that are animated, see artist'],
['ann','Annotator',
'A person who makes manuscript annotations on an item'],
['apl','Appellant',
'A person or organization who appeals a lower court\'s decision'],
['ape','Appellee',
'A person or organization against whom an appeal is taken'],
['app','Applicant',
'A  person or organization responsible for the submission of an application or who is named as eligible for the results of the processing of the application (e.g., bestowing of rights, reward, title, position)'],
['arc','Architect',
'A person, family, or organization responsible for creating an architectural design, including a pictorial representation intended to show how a building, etc., will look when completed. It also oversees the construction of structures'],
['arr','Arranger',
'A person, family, or organization contributing to a musical work by rewriting the composition for a medium of performance different from that for which the work was originally intended, or modifying the work for the same medium of performance, etc., such that the musical substance of the original composition remains essentially unchanged. For extensive modification that effectively results in the creation of a new musical work, see composer'],
['acp','Art copyist',
'A person (e.g., a painter or sculptor) who makes copies of works of visual art'],
['adi','Art director',
'A person contributing to a motion picture or television production by overseeing the artists and craftspeople who build the sets'],
['art','Artist',
'A person, family, or organization responsible for creating a work by conceiving, and implementing, an original graphic design, drawing, painting, etc. For book illustrators, prefer Illustrator [ill]'],
['ard','Artistic director',
'A person responsible for controlling the development of the artistic style of an entire production, including the choice of works to be presented and selection of senior production staff'],
['asg','Assignee',
'A person or organization to whom a license for printing or publishing has been transferred'],
['asn','Associated name',
'A person or organization associated with or found in an item or collection, which cannot be determined to be that of a Former owner [fmo] or other designated relationship indicative of provenance'],
['att','Attributed name',
'An author, artist, etc., relating him/her to a resource for which there is or once was substantial authority for designating that person as author, creator, etc. of the work'],
['auc','Auctioneer',
'A person or organization in charge of the estimation and public auctioning of goods, particularly books, artistic works, etc.'],
['aut','Author',
'A person, family, or organization responsible for creating a work that is primarily textual in content, regardless of media type (e.g., printed text, spoken word, electronic text, tactile text) or genre (e.g., poems, novels, screenplays, blogs). Use also for persons, etc., creating a new work by paraphrasing, rewriting, or adapting works by another creator such that the modification has substantially changed the nature and content of the original or changed the medium of expression'],
['aqt','Author in quotations or text abstracts',
'A person or organization whose work is largely quoted or extracted in works to which he or she did not contribute directly. Such quotations are found particularly in exhibition catalogs, collections of photographs, etc.'],
['aft','Author of afterword, colophon, etc.',
'A person or organization responsible for an afterword, postface, colophon, etc. but who is not the chief author of a work'],
['aud','Author of dialog',
'A person or organization responsible for the dialog or spoken commentary for a screenplay or sound recording'],
['aui','Author of introduction, etc.',
'A person or organization responsible for an introduction, preface, foreword, or other critical introductory matter, but who is not the chief author'],
['ato','Autographer',
'A person whose manuscript signature appears on an item'],
['ant','Bibliographic antecedent',
'A person or organization responsible for a resource upon which the resource represented by the bibliographic description is based. This may be appropriate for adaptations, sequels, continuations, indexes, etc.'],
['bnd','Binder',
'A person who binds an item'],
['bdd','Binding designer',
'A person or organization responsible for the binding design of a book, including the type of binding, the type of materials used, and any decorative aspects of the binding'],
['blw','Blurb writer',
'A person or organization responsible for writing a commendation or testimonial for a work, which appears on or within the publication itself, frequently on the back or dust jacket of print publications or on advertising material for all media'],
['bkd','Book designer',
'A person or organization involved in manufacturing a manifestation by being responsible for the entire graphic design of a book, including arrangement of type and illustration, choice of materials, and process used'],
['bkp','Book producer',
'A person or organization responsible for the production of books and other print media'],
['bjd','Bookjacket designer',
'A person or organization responsible for the design of flexible covers designed for or published with a book, including the type of materials used, and any decorative aspects of the bookjacket'],
['bpd','Bookplate designer',
'A person or organization responsible for the design of a book owner\'s identification label that is most commonly pasted to the inside front cover of a book'],
['bsl','Bookseller',
'A person or organization who makes books and other bibliographic materials available for purchase. Interest in the materials is primarily lucrative'],
['brl','Braille embosser',
'A person, family, or organization involved in manufacturing a resource by embossing Braille cells using a stylus, special embossing printer, or other device'],
['brd','Broadcaster',
'A person, family, or organization involved in broadcasting a resource to an audience via radio, television, webcast, etc.'],
['cll','Calligrapher',
'A person or organization who writes in an artistic hand, usually as a copyist and or engrosser'],
['ctg','Cartographer',
'A person, family, or organization responsible for creating a map, atlas, globe, or other cartographic work'],
['cas','Caster',
'A person, family, or organization involved in manufacturing a resource by pouring a liquid or molten substance into a mold and leaving it to solidify to take the shape of the mold'],
['cns','Censor',
'A person or organization who examines bibliographic resources for the purpose of suppressing parts deemed objectionable on moral, political, military, or other grounds'],
['chr','Choreographer',
'A person responsible for creating or contributing to a work of movement'],
['cng','Cinematographer',
'A person in charge of photographing a motion picture, who plans the technical aspets of lighting and photographing of scenes, and often assists the director in the choice of angles, camera setups, and lighting moods. He or she may also supervise the further processing of filmed material up to the completion of the work print. Cinematographer is also referred to as director of photography. Do not confuse with videographer'],
['cli','Client',
'A person or organization for whom another person or organization is acting'],
['cor','Collection registrar',
'A curator who lists or inventories the items in an aggregate work such as a collection of items or works'],
['col','Collector',
'A curator who brings together items from various sources that are then arranged, described, and cataloged as a collection. A collector is neither the creator of the material nor a person to whom manuscripts in the collection may have been addressed'],
['clt','Collotyper',
'A person, family, or organization involved in manufacturing a manifestation of photographic prints from film or other colloid that has ink-receptive and ink-repellent surfaces'],
['clr','Colorist',
'A person or organization responsible for applying color to drawings, prints, photographs, maps, moving images, etc'],
['cmm','Commentator',
'A performer contributing to a work by providing interpretation, analysis, or a discussion of the subject matter on a recording, film, or other audiovisual medium'],
['cwt','Commentator for written text',
'A person or organization responsible for the commentary or explanatory notes about a text. For the writer of manuscript annotations in a printed book, use Annotator'],
['com','Compiler',
'A person, family, or organization responsible for creating a new work (e.g., a bibliography, a directory) through the act of compilation, e.g., selecting, arranging, aggregating, and editing data, information, etc'],
['cpl','Complainant',
'A person or organization who applies to the courts for redress, usually in an equity proceeding'],
['cpt','Complainant-appellant',
'A complainant who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding'],
['cpe','Complainant-appellee',
'A complainant against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding'],
['cmp','Composer',
'A person, family, or organization responsible for creating or contributing to a musical resource by adding music to a work that originally lacked it or supplements it'],
['cmt','Compositor',
'A person or organization responsible for the creation of metal slug, or molds made of other materials, used to produce the text and images in printed matter'],
['ccp','Conceptor',
'A person or organization responsible for the original idea on which a work is based, this includes the scientific author of an audio-visual item and the conceptor of an advertisement'],
['cnd','Conductor',
'A performer contributing to a musical resource by leading a performing group (orchestra, chorus, opera, etc.) in a musical or dramatic presentation, etc.'],
['con','Conservator',
'A person or organization responsible for documenting, preserving, or treating printed or manuscript material, works of art, artifacts, or other media'],
['csl','Consultant',
'A person or organization relevant to a resource, who is called upon for professional advice or services in a specialized field of knowledge or training'],
['csp','Consultant to a project',
'A person or organization relevant to a resource, who is engaged specifically to provide an intellectual overview of a strategic or operational task and by analysis, specification, or instruction, to create or propose a cost-effective course of action or solution'],
['cos','Contestant',
'A person(s) or organization who opposes, resists, or disputes, in a court of law, a claim, decision, result, etc.'],
['cot','Contestant-appellant',
'A contestant who takes an appeal from one court of law or jurisdiction to another to reverse the judgment'],
['coe','Contestant-appellee',
'A contestant against whom an appeal is taken from one court of law or jurisdiction to another to reverse the judgment'],
['cts','Contestee',
'A person(s) or organization defending a claim, decision, result, etc. being opposed, resisted, or disputed in a court of law'],
['ctt','Contestee-appellant',
'A contestee who takes an appeal from one court or jurisdiction to another to reverse the judgment'],
['cte','Contestee-appellee',
'A contestee against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment'],
['ctr','Contractor',
'A person or organization relevant to a resource, who enters into a contract with another person or organization to perform a specific'],
['ctb','Contributor',
'A person, family or organization responsible for making contributions to the resource. This includes those whose work has been contributed to a larger work, such as an anthology, serial publication, or other compilation of individual works. If a more specific role is available, prefer that, e.g. editor, compiler, illustrator'],
['cpc','Copyright claimant',
'A person or organization listed as a copyright owner at the time of registration. Copyright can be granted or later transferred to another person or organization, at which time the claimant becomes the copyright holder'],
['cph','Copyright holder',
'A person or organization to whom copy and legal rights have been granted or transferred for the intellectual content of a work. The copyright holder, although not necessarily the creator of the work, usually has the exclusive right to benefit financially from the sale and use of the work to which the associated copyright protection applies'],
['crr','Corrector',
'A person or organization who is a corrector of manuscripts, such as the scriptorium official who corrected the work of a scribe. For printed matter, use Proofreader'],
['crp','Correspondent',
'A person or organization who was either the writer or recipient of a letter or other communication'],
['cst','Costume designer',
'A person, family, or organization that designs the costumes for a moving image production or for a musical or dramatic presentation or entertainment'],
['cou','Court governed',
'A court governed by court rules, regardless of their official nature (e.g., laws, administrative regulations)'],
['crt','Court reporter',
'A person, family, or organization contributing to a resource by preparing a court\'s opinions for publication'],
['cov','Cover designer',
'A person or organization responsible for the graphic design of a book cover, album cover, slipcase, box, container, etc. For a person or organization responsible for the graphic design of an entire book, use Book designer; for book jackets, use Bookjacket designer'],
['cre','Creator',
'A person or organization responsible for the intellectual or artistic content of a resource'],
['cur','Curator',
'A person, family, or organization conceiving, aggregating, and/or organizing an exhibition, collection, or other item'],
['dnc','Dancer',
'A performer who dances in a musical, dramatic, etc., presentation'],
['dtc','Data contributor',
'A person or organization that submits data for inclusion in a database or other collection of data'],
['dtm','Data manager',
'A person or organization responsible for managing databases or other data sources'],
['dte','Dedicatee',
'A person, family, or organization to whom a resource is dedicated'],
['dto','Dedicator',
'A person who writes a dedication, which may be a formal statement or in epistolary or verse form'],
['dfd','Defendant',
'A person or organization who is accused in a criminal proceeding or sued in a civil proceeding'],
['dft','Defendant-appellant',
'A defendant who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in a legal action'],
['dfe','Defendant-appellee',
'A defendant against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in a legal action'],
['dgg','Degree granting institution',
'A organization granting an academic degree'],
['dgs','Degree supervisor',
'A person overseeing a higher level academic degree'],
['dln','Delineator',
'A person or organization executing technical drawings from others\' designs'],
['dpc','Depicted',
'An entity depicted or portrayed in a work, particularly in a work of art'],
['dpt','Depositor',
'A current owner of an item who deposited the item into the custody of another person, family, or organization, while still retaining ownership'],
['dsr','Designer',
'A person, family, or organization responsible for creating a design for an object'],
['drt','Director',
'A person responsible for the general management and supervision of a filmed performance, a radio or television program, etc.'],
['dis','Dissertant',
'A person who presents a thesis for a university or higher-level educational degree'],
['dbp','Distribution place',
'A place from which a resource, e.g., a serial, is distributed'],
['dst','Distributor',
'A person or organization that has exclusive or shared marketing rights for a resource'],
['dnr','Donor',
'A former owner of an item who donated that item to another owner'],
['drm','Draftsman',
'A person, family, or organization contributing to a resource by an architect, inventor, etc., by making detailed plans or drawings for buildings, ships, aircraft, machines, objects, etc'],
['dub','Dubious author',
'A person or organization to which authorship has been dubiously or incorrectly ascribed'],
['edt','Editor',
'A person, family, or organization contributing to a resource by revising or elucidating the content, e.g., adding an introduction, notes, or other critical matter. An editor may also prepare a resource for production, publication, or distribution. For major revisions, adaptations, etc., that substantially change the nature and content of the original work, resulting in a new work, see author'],
['edc','Editor of compilation',
'A person, family, or organization contributing to a collective or aggregate work by selecting and putting together works, or parts of works, by one or more creators. For compilations of data, information, etc., that result in new works, see compiler'],
['edm','Editor of moving image work',
'A person, family, or organization responsible for assembling, arranging, and trimming film, video, or other moving image formats, including both visual and audio aspects'],
['elg','Electrician',
'A person responsible for setting up a lighting rig and focusing the lights for a production, and running the lighting at a performance'],
['elt','Electrotyper',
'A person or organization who creates a duplicate printing surface by pressure molding and electrodepositing of metal that is then backed up with lead for printing'],
['enj','Enacting jurisdiction',
'A jurisdiction enacting a law, regulation, constitution, court rule, etc.'],
['eng','Engineer',
'A person or organization that is responsible for technical planning and design, particularly with construction'],
['egr','Engraver',
'A person or organization who cuts letters, figures, etc. on a surface, such as a wooden or metal plate used for printing'],
['etr','Etcher',
'A person or organization who produces text or images for printing by subjecting metal, glass, or some other surface to acid or the corrosive action of some other substance'],
['evp','Event place',
'A place where an event such as a conference or a concert took place'],
['exp','Expert',
'A person or organization in charge of the description and appraisal of the value of goods, particularly rare items, works of art, etc.'],
['fac','Facsimilist',
'A person or organization that executed the facsimile'],
['fld','Field director',
'A person or organization that manages or supervises the work done to collect raw data or do research in an actual setting or environment (typically applies to the natural and social sciences)'],
['fmd','Film director',
'A director responsible for the general management and supervision of a filmed performance'],
['fds','Film distributor',
'A person, family, or organization involved in distributing a moving image resource to theatres or other distribution channels'],
['flm','Film editor',
'A person who, following the script and in creative cooperation with the Director, selects, arranges, and assembles the filmed material, controls the synchronization of picture and sound, and participates in other post-production tasks such as sound mixing and visual effects processing.  Today, picture editing is often performed digitally.'],
['fmp','Film producer',
'A producer responsible for most of the business aspects of a film'],
['fmk','Filmmaker',
'A person, family or organization responsible for creating an independent or personal film. A filmmaker is individually responsible for the conception and execution of all aspects of the film'],
['fpy','First party',
'A person or organization who is identified as the only party or the party of the first party. In the case of transfer of rights, this is the assignor, transferor, licensor, grantor, etc. Multiple parties can be named jointly as the first party'],
['frg','Forger',
'A person or organization who makes or imitates something of value or importance, especially with the intent to defraud'],
['fmo','Former owner',
'A person, family, or organization formerly having legal possession of an item'],
['fnd','Funder',
'A person or organization that furnished financial support for the production of the work'],
['gis','Geographic information specialist',
'A person responsible for geographic information system (GIS) development and integration with global positioning system data'],
['hnr','Honoree',
'A person, family, or organization honored by a work or item (e.g., the honoree of a festschrift, a person to whom a copy is presented)'],
['hst','Host',
'A performer contributing to a resource by leading a program (often broadcast) that includes other guests, performers, etc. (e.g., talk show host)'],
['his','Host institution',
'An organization hosting the event, exhibit, conference, etc., which gave rise to a resource, but having little or no responsibility for the content of the resource'],
['ilu','Illuminator',
'A person providing decoration to a specific item using precious metals or color, often with elaborate designs and motifs'],
['ill','Illustrator',
'A person, family, or organization contributing to a resource by supplementing the primary content with drawings, diagrams, photographs, etc. If the work is primarily the artistic content created by this entity, use artist or photographer'],
['ins','Inscriber',
'A person who has written a statement of dedication or gift'],
['itr','Instrumentalist',
'A performer contributing to a resource by playing a musical instrument'],
['ive','Interviewee',
'A person, family or organization responsible for creating or contributing to a resource by responding to an interviewer, usually a reporter, pollster, or some other information gathering agent'],
['ivr','Interviewer',
'A person, family, or organization responsible for creating or contributing to a resource by acting as an interviewer, reporter, pollster, or some other information gathering agent'],
['inv','Inventor',
'A person, family, or organization responsible for creating a new device or process'],
['isb','Issuing body',
'A person, family or organization issuing a work, such as an official organ of the body'],
['jud','Judge',
'A person who hears and decides on legal matters in court.'],
['jug','Jurisdiction governed',
'A jurisdiction governed by a law, regulation, etc., that was enacted by another jurisdiction'],
['lbr','Laboratory',
'An organization that provides scientific analyses of material samples'],
['ldr','Laboratory director',
'A person or organization that manages or supervises work done in a controlled setting or environment'],
['lsa','Landscape architect',
'An architect responsible for creating landscape works. This work involves coordinating the arrangement of existing and proposed land features and structures'],
['led','Lead',
'A person or organization that takes primary responsibility for a particular activity or endeavor. May be combined with another relator term or code to show the greater importance this person or organization has regarding that particular role. If more than one relator is assigned to a heading, use the Lead relator only if it applies to all the relators'],
['len','Lender',
'A person or organization permitting the temporary use of a book, manuscript, etc., such as for photocopying or microfilming'],
['lil','Libelant',
'A person or organization who files a libel in an ecclesiastical or admiralty case'],
['lit','Libelant-appellant',
'A libelant who takes an appeal from one ecclesiastical court or admiralty to another to reverse the judgment'],
['lie','Libelant-appellee',
'A libelant against whom an appeal is taken from one ecclesiastical court or admiralty to another to reverse the judgment'],
['lel','Libelee',
'A person or organization against whom a libel has been filed in an ecclesiastical court or admiralty'],
['let','Libelee-appellant',
'A libelee who takes an appeal from one ecclesiastical court or admiralty to another to reverse the judgment'],
['lee','Libelee-appellee',
'A libelee against whom an appeal is taken from one ecclesiastical court or admiralty to another to reverse the judgment'],
['lbt','Librettist',
'An author of a libretto of an opera or other stage work, or an oratorio'],
['lse','Licensee',
'A person or organization who is an original recipient of the right to print or publish'],
['lso','Licensor',
'A person or organization who is a signer of the license, imprimatur, etc'],
['lgd','Lighting designer',
'A person or organization who designs the lighting scheme for a theatrical presentation, entertainment, motion picture, etc.'],
['ltg','Lithographer',
'A person or organization who prepares the stone or plate for lithographic printing, including a graphic artist creating a design directly on the surface from which printing will be done.'],
['lyr','Lyricist',
'An author of the words of a non-dramatic musical work (e.g. the text of a song), except for oratorios'],
['mfp','Manufacture place',
'The place of manufacture (e.g., printing, duplicating, casting, etc.) of a resource in a published form'],
['mfr','Manufacturer',
'A person or organization responsible for printing, duplicating, casting, etc. a resource'],
['mrb','Marbler',
'The entity responsible for marbling paper, cloth, leather, etc. used in construction of a resource'],
['mrk','Markup editor',
'A person or organization performing the coding of SGML, HTML, or XML markup of metadata, text, etc.'],
['med','Medium',
'A person held to be a channel of communication between the earthly world and a world'],
['mdc','Metadata contact',
'A person or organization primarily responsible for compiling and maintaining the original description of a metadata set (e.g., geospatial metadata set)'],
['mte','Metal-engraver',
'An engraver responsible for decorations, illustrations, letters, etc. cut on a metal surface for printing or decoration'],
['mtk','Minute taker',
'A person, family, or organization responsible for recording the minutes of a meeting'],
['mod','Moderator',
'A performer contributing to a resource by leading a program (often broadcast) where topics are discussed, usually with participation of experts in fields related to the discussion'],
['mon','Monitor',
'A person or organization that supervises compliance with the contract and is responsible for the report and controls its distribution. Sometimes referred to as the grantee, or controlling agency'],
['mcp','Music copyist',
'A person who transcribes or copies musical notation'],
['msd','Musical director',
'A person who coordinates the activities of the composer, the sound editor, and sound mixers for a moving image production or for a musical or dramatic presentation or entertainment'],
['mus','Musician',
'A person or organization who performs music or contributes to the musical content of a work when it is not possible or desirable to identify the function more precisely'],
['nrt','Narrator',
'A performer contributing to a resource by reading or speaking in order to give an account of an act, occurrence, course of events, etc'],
['osp','Onscreen presenter',
'A performer contributing to an expression of a work by appearing on screen in nonfiction moving image materials or introductions to fiction moving image materials to provide contextual or background information. Use when another term (e.g., narrator, host) is either not applicable or not desired'],
['opn','Opponent',
'A person or organization responsible for opposing a thesis or dissertation'],
['orm','Organizer',
'A person, family, or organization organizing the exhibit, event, conference, etc., which gave rise to a resource'],
['org','Originator',
'A person or organization performing the work, i.e., the name of a person or organization associated with the intellectual content of the work. This category does not include the publisher or personal affiliation, or sponsor except where it is also the corporate author'],
['oth','Other',
'A role that has no equivalent in the MARC list.'],
['own','Owner',
'A person, family, or organization that currently owns an item or collection, i.e.has legal possession of a resource'],
['pan','Panelist',
'A performer contributing to a resource by participating in a program (often broadcast) where topics are discussed, usually with participation of experts in fields related to the discussion'],
['ppm','Papermaker',
'A person or organization responsible for the production of paper, usually from wood, cloth, or other fibrous material'],
['pta','Patent applicant',
'A person or organization that applied for a patent'],
['pth','Patent holder',
'A person or organization that was granted the patent referred to by the item'],
['pat','Patron',
'A person or organization responsible for commissioning a work. Usually a patron uses his or her means or influence to support the work of artists, writers, etc. This includes those who commission and pay for individual works'],
['prf','Performer',
'A person contributing to a resource by performing music, acting, dancing, speaking, etc., often in a musical or dramatic presentation, etc. If specific codes are used, [prf] is used for a person whose principal skill is not known or specified'],
['pma','Permitting agency',
'An organization (usually a government agency) that issues permits under which work is accomplished'],
['pht','Photographer',
'A person, family, or organization responsible for creating a photographic work'],
['ptf','Plaintiff',
'A person or organization who brings a suit in a civil proceeding'],
['ptt','Plaintiff-appellant',
'A plaintiff who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in a legal proceeding'],
['pte','Plaintiff-appellee',
'A plaintiff against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in a legal proceeding'],
['plt','Platemaker',
'A person, family, or organization involved in manufacturing a manifestation by preparing plates used in the production of printed images and/or text'],
['pra','Praeses',
'A person who is the faculty moderator of an academic disputation, normally proposing a thesis and participating in the ensuing disputation'],
['pre','Presenter',
'A person or organization mentioned in an “X presents” credit for moving image materials and who is associated with production, finance, or distribution in some way.  A vanity credit;  in early years, normally the head of a studio'],
['prt','Printer',
'A person, family, or organization involved in manufacturing a manifestation of printed text, notated music, etc., from type or plates, such as a book, newspaper, magazine, broadside, score, etc'],
['pop','Printer of plates',
'A person or organization who prints illustrations from plates.'],
['prm','Printmaker',
'A person or organization who makes a relief, intaglio, or planographic printing surface'],
['prc','Process contact',
'A person or organization primarily responsible for performing or initiating a process, such as is done with the collection of metadata sets'],
['pro','Producer',
'A person, family, or organization responsible for most of the business aspects of a production for screen, audio recording, television, webcast, etc. The producer is generally responsible for fund raising, managing the production, hiring key personnel, arranging for distributors, etc.'],
['prn','Production company',
'An organization that is responsible for financial, technical, and organizational management of a production for stage, screen, audio recording, television, webcast, etc.'],
['prs','Production designer',
'A person or organization responsible for designing the overall visual appearance of a moving image production'],
['pmn','Production manager',
'A person responsible for all technical and business matters in a production'],
['prd','Production personnel',
'A person or organization associated with the production (props, lighting, special effects, etc.) of a musical or dramatic presentation or entertainment'],
['prp','Production place',
'The place of production (e.g., inscription, fabrication, construction, etc.) of a resource in an unpublished form'],
['prg','Programmer',
'A person, family, or organization responsible for creating a computer program'],
['pdr','Project director',
'A person or organization with primary responsibility for all essential aspects of a project, has overall responsibility for managing projects, or provides overall direction to a project manager'],
['pfr','Proofreader',
'A person who corrects printed matter. For manuscripts, use Corrector [crr]'],
['prv','Provider',
'A person or organization who produces, publishes, manufactures, or distributes a resource if specific codes are not desired (e.g. [mfr], [pbl])'],
['pup','Publication place',
'The place where a resource is published'],
['pbl','Publisher',
'A person or organization responsible for publishing, releasing, or issuing a resource'],
['pbd','Publishing director',
'A person or organization who presides over the elaboration of a collective work to ensure its coherence or continuity. This includes editors-in-chief, literary editors, editors of series, etc.'],
['ppt','Puppeteer',
'A performer contributing to a resource by manipulating, controlling, or directing puppets or marionettes in a moving image production or a musical or dramatic presentation or entertainment'],
['rdd','Radio director',
'A director responsible for the general management and supervision of a radio program'],
['rpc','Radio producer',
'A producer responsible for most of the business aspects of a radio program'],
['rce','Recording engineer',
'A person contributing to a resource by supervising the technical aspects of a sound or video recording session'],
['rcd','Recordist',
'A person or organization who uses a recording device to capture sounds and/or video during a recording session, including field recordings of natural sounds, folkloric events, music, etc.'],
['red','Redaktor',
'A person or organization who writes or develops the framework for an item without being intellectually responsible for its content'],
['ren','Renderer',
'A person or organization who prepares drawings of architectural designs (i.e., renderings) in accurate, representational perspective to show what the project will look like when completed'],
['rpt','Reporter',
'A person or organization who writes or presents reports of news or current events on air or in print'],
['rps','Repository',
'An organization that hosts data or material culture objects and provides services to promote long term, consistent and shared use of those data or objects'],
['rth','Research team head',
'A person who directed or managed a research project'],
['rtm','Research team member',
'A person who participated in a research project but whose role did not involve direction or management of it'],
['res','Researcher',
'A person or organization responsible for performing research'],
['rsp','Respondent',
'A person or organization who makes an answer to the courts pursuant to an application for redress (usually in an equity proceeding) or a candidate for a degree who defends or opposes a thesis provided by the praeses in an academic disputation'],
['rst','Respondent-appellant',
'A respondent who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding'],
['rse','Respondent-appellee',
'A respondent against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding'],
['rpy','Responsible party',
'A person or organization legally responsible for the content of the published material'],
['rsg','Restager',
'A person or organization, other than the original choreographer or director, responsible for restaging a choreographic or dramatic work and who contributes minimal new content'],
['rsr','Restorationist',
'A person, family, or organization responsible for the set of technical, editorial, and intellectual procedures aimed at compensating for the degradation of an item by bringing it back to a state as close as possible to its original condition'],
['rev','Reviewer',
'A person or organization responsible for the review of a book, motion picture, performance, etc.'],
['rbr','Rubricator',
'A person or organization responsible for parts of a work, often headings or opening parts of a manuscript, that appear in a distinctive color, usually red'],
['sce','Scenarist',
'A person or organization who is the author of a motion picture screenplay, generally the person who wrote the scenarios for a motion picture during the silent era'],
['sad','Scientific advisor',
'A person or organization who brings scientific, pedagogical, or historical competence to the conception and realization on a work, particularly in the case of audio-visual items'],
['aus','Screenwriter',
'An author of a screenplay, script, or scene'],
['scr','Scribe',
'A person who is an amanuensis and for a writer of manuscripts proper. For a person who makes pen-facsimiles, use Facsimilist [fac]'],
['scl','Sculptor',
'An artist responsible for creating a three-dimensional work by modeling, carving, or similar technique'],
['spy','Second party',
'A person or organization who is identified as the party of the second part. In the case of transfer of right, this is the assignee, transferee, licensee, grantee, etc. Multiple parties can be named jointly as the second party'],
['sec','Secretary',
'A person or organization who is a recorder, redactor, or other person responsible for expressing the views of a organization'],
['sll','Seller',
'A former owner of an item who sold that item to another owner'],
['std','Set designer',
'A person who translates the rough sketches of the art director into actual architectural structures for a theatrical presentation, entertainment, motion picture, etc. Set designers draw the detailed guides and specifications for building the set'],
['stg','Setting',
'An entity in which the activity or plot of a work takes place, e.g. a geographic place, a time period, a building, an event'],
['sgn','Signer',
'A person whose signature appears without a presentation or other statement indicative of provenance. When there is a presentation statement, use Inscriber [ins].'],
['sng','Singer',
'A performer contributing to a resource by using his/her/their voice, with or without instrumental accompaniment, to produce music. A singer\'s performance may or may not include actual words'],
['sds','Sound designer',
'A person who produces and reproduces the sound score (both live and recorded), the installation of microphones, the setting of sound levels, and the coordination of sources of sound for a production'],
['spk','Speaker',
'A performer contributing to a resource by speaking words, such as a lecture, speech, etc.'],
['spn','Sponsor',
'A person, family, or organization sponsoring some aspect of a resource, e.g., funding research, sponsoring an event'],
['sgd','Stage director',
'A person or organization contributing to a stage resource through the overall management and supervision of a performance'],
['stm','Stage manager',
'A person who is in charge of everything that occurs on a performance stage, and who acts as chief of all crews and assistant to a director during rehearsals'],
['stn','Standards body',
'An organization responsible for the development or enforcement of a standard'],
['str','Stereotyper',
'A person or organization who creates a new plate for printing by molding or copying another printing surface'],
['stl','Storyteller',
'A performer contributing to a resource by relaying a creator\'s original story with dramatic or theatrical interpretation'],
['sht','Supporting host',
'A person or organization that supports (by allocating facilities, staff, or other resources) a project, program, meeting, event, data objects, material culture objects, or other entities capable of support'],
['srv','Surveyor',
'A person, family, or organization contributing to a cartographic resource by providing measurements or dimensional relationships for the geographic area represented'],
['tch','Teacher',
'A performer contributing to a resource by giving instruction or providing a demonstration'],
['tcd','Technical director',
'A person who is ultimately in charge of scenery, props, lights and sound for a production'],
['tld','Television director',
'A director responsible for the general management and supervision of a television program'],
['tlp','Television producer',
'A producer responsible for most of the business aspects of a television program'],
['ths','Thesis advisor',
'A person under whose supervision a degree candidate develops and presents a thesis, mémoire, or text of a dissertation'],
['trc','Transcriber',
'A person, family, or organization contributing to a resource by changing it from one system of notation to another. For a work transcribed for a different instrument or performing group, see Arranger [arr]. For makers of pen-facsimiles, use Facsimilist [fac]'],
['trl','Translator',
'A person or organization who renders a text from one language into another, or from an older form of a language into the modern form'],
['tyd','Type designer',
'A person or organization who designs the type face used in a particular item'],
['tyg','Typographer',
'A person or organization primarily responsible for choice and arrangement of type used in an item. If the typographer is also responsible for other aspects of the graphic design of a book (e.g., Book designer [bkd]), codes for both functions may be needed'],
['uvp','University place',
'A place where a university that is associated with a resource is located, for example, a university where an academic dissertation or thesis was presented'],
['vdg','Videographer',
'A person in charge of a video production, e.g. the video recording of a stage production as opposed to a commercial motion picture. The videographer may be the camera operator or may supervise one or more camera operators. Do not confuse with cinematographer'],
['vac','Voice actor',
'An actor contributing to a resource by providing the voice for characters in radio and audio productions and for animated characters in moving image works, as well as by providing voice overs in radio and television commercials, dubbed resources, etc.'],
['wit','Witness',
'Use for a person who verifies the truthfulness of an event or action.'],
['wde','Wood engraver',
'A person or organization who makes prints by cutting the image in relief on the end-grain of a wood block'],
['wdc','Woodcutter',
'A person or organization who makes prints by cutting the image in relief on the plank side of a wood block'],
['wam','Writer of accompanying material',
'A person or organization who writes significant material which accompanies a sound recording or other audiovisual material'],
['wac','Writer of added commentary',
'A person, family, or organization contributing to an expression of a work by providing an interpretation or critical explanation of the original work'],
['wal','Writer of added lyrics',
'A writer of words added to an expression of a musical work. For lyric writing in collaboration with a composer to form an original work, see lyricist'],
['wat','Writer of added text',
'A person, family, or organization contributing to a non-textual resource by providing text for the non-textual work (e.g., writing captions for photographs, descriptions of maps).'],
['win','Writer of introduction',
'A person, family, or organization contributing to a resource by providing an introduction to the original work'],
['wpr','Writer of preface',
'A person, family, or organization contributing to a resource by providing a preface to the original work'],
['wst','Writer of supplementary textual content',
'A person, family, or organization contributing to a resource by providing supplementary textual content (e.g., an introduction, a preface) to the original work'],
]

#
#
#[file_format_extension VARCHAR(7), file_format_mime VARCHAR(255), file_format_hrname]
FILE_FORMAT = [
	['.pdf', 'application/pdf', 'Adobe Portable Document Format'],
	['.aac', 'audio/x-aac', 'Advanced Audio Coding (AAC)'],
	['.dts', 'audio/vnd.dts', 'DTS Audio'],
	['.dtshd', 'audio/vnd.dts.hd', 'DTS High Definition Audio'],
	['.f4v', 'video/x-f4v', 'Flash Video'],
	['.flv', 'video/x-flv', 'Flash Video'],
	['.h264', 'video/h264', 'H.264'],
	['.html', 'text/html', 'HyperText Markup Language (HTML)'],
	['.xls', 'application/vnd.ms-excel', 'Microsoft Excel'],
	['.xlam', 'application/vnd.ms-excel.addin.macroenabled.12', 'Microsoft Excel - Add-In File'],
	['.xlsb', 'application/vnd.ms-excel.sheet.binary.macroenabled.12', 'Microsoft Excel - Binary Workbook'],
	['.xltm', 'application/vnd.ms-excel.template.macroenabled.12', 'Microsoft Excel - Macro-Enabled Template File'],
	['.xlsm', 'application/vnd.ms-excel.sheet.macroenabled.12', 'Microsoft Excel - Macro-Enabled Workbook'],
	['.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Microsoft Office - OOXML - Spreadsheet'],
	['.xltx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template', 'Microsoft Office - OOXML - Spreadsheet Template'],
	['.mp4a', 'audio/mp4', 'MPEG-4 Audio'],
	['.mp4', 'video/mp4', 'MPEG-4 Video'],
	['.svg', 'image/svg+xml', 'Scalable Vector Graphics (SVG)'],
	['.tiff', 'image/tiff', 'Tagged Image File Format'],
	['.wav', 'audio/x-wav', 'Waveform Audio File Format (WAV)'],
	['.xhtml', 'application/xhtml+xml', 'XHTML - The Extensible HyperText Markup Language'],
	['.xml', 'application/xml', 'XML - Extensible Markup Language'],
	['.aif', 'audio/x-aiff', 'Audio Interchange File Format'],
	['.webm', 'video/webm', 'Open Web Media Project - Video'],
	['.weba', 'audio/webm', 'Open Web Media Project - Audio'],
	['.webp', 'image/webp', 'WebP Image'],
	['.bmp', 'image/bmp', 'Bitmap Image File'],
	['.sub', 'image/vnd.dvb.subtitle', 'Close Captioning - Subtitle'],
	['.gif', 'image/gif', 'Graphics Interchange Format'],
	['.ico', 'image/x-icon', 'Icon Image'],
	['.jpg', 'image/jpeg', 'JPEG Image'],
	['.png', 'image/png', 'Portable Network Graphics (PNG)'],
]

#
#
#[genre_id TINYINT(255), genre VARCHAR(63), description TEXT(1023)]
GENRE = [
[0,'Bibliography','Description for Bibliography'],
[1,'Catalog','Description for Catalog'],
[2,'Citation','Description for Citation'],
[3,'Collection','Description for Collection'],
[4,'Correspondence','Description for Correspondence'],
[5,'Criticism','Description for Criticism'],
[6,'Drama','Description for Drama'],
[7,'Ephemera','Description for Ephemera'],
[8,'Fiction','Description for Fiction'],
[9,'Historiography','Description for Historiography'],
[10,'Law','Description for Law'],
[11,'Life Writing','Description for Life Writing'],
[12,'Liturgy','Description for Liturgy'],
[13,'Musical Analysis','Description for Musical Analysis'],
[14,'Music, Other','Description for Music, Other'],
[15,'Musical Recording','Description for Musical Recording'],
[16,'Musical Score','Description for Musical Score'],
[17,'Nonfiction','Description for Nonfiction'],
[18,'Paratext','Description for Paratext'],
[19,'Philosophy','Description for Philosophy'],
[20,'Photograph','Description for Photograph'],
[21,'Poetry','Description for Poetry'],
[22,'Religion','Description for Religion'],
[23,'Religion, Other','Description for Religion, Other'],
[24,'Reference Works','Description for Reference Works'],
[25,'Review','Description for Review'],
[26,'Scripture','Description for Scripture'],
[27,'Sermon','Description for Sermon'],
[28,'Translation','Description for Translation'],
[29,'Travel Writing','Description for Travel Writing'],
[30,'Unspecified','Description for Unspecified'],
[31,'Visual Art','Description for Visual Art'],
]

#
#
#[language VARCHAR(3), language_full VARCHAR(127)]
LANGUAGE = [
['aar','Afar'],
['abk','Abkhazian'],
['ace','Achinese'],
['ach','Acoli'],
['ada','Adangme'],
['ady','Adyghe; Adygei'],
['afa','Afro-Asiatic languages'],
['afh','Afrihili'],
['afr','Afrikaans'],
['ain','Ainu'],
['aka','Akan'],
['akk','Akkadian'],
['alb','Albanian'],
['ale','Aleut'],
['alg','Algonquian languages'],
['alt','Southern Altai'],
['amh','Amharic'],
['ang','English, Old (ca.450-1100)'],
['anp','Angika'],
['apa','Apache languages'],
['ara','Arabic'],
['arc','Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'],
['arg','Aragonese'],
['arm','Armenian'],
['arn','Mapudungun; Mapuche'],
['arp','Arapaho'],
['art','Artificial languages'],
['arw','Arawak'],
['asm','Assamese'],
['ast','Asturian; Bable; Leonese; Asturleonese'],
['ath','Athapascan languages'],
['aus','Australian languages'],
['ava','Avaric'],
['ave','Avestan'],
['awa','Awadhi'],
['aym','Aymara'],
['aze','Azerbaijani'],
['bad','Banda languages'],
['bai','Bamileke languages'],
['bak','Bashkir'],
['bal','Baluchi'],
['bam','Bambara'],
['ban','Balinese'],
['baq','Basque'],
['bas','Basa'],
['bat','Baltic languages'],
['bej','Beja; Bedawiyet'],
['bel','Belarusian'],
['bem','Bemba'],
['ben','Bengali'],
['ber','Berber languages'],
['bho','Bhojpuri'],
['bih','Bihari languages'],
['bik','Bikol'],
['bin','Bini; Edo'],
['bis','Bislama'],
['bla','Siksika'],
['bnt','Bantu languages'],
['tib','Tibetan'],
['bos','Bosnian'],
['bra','Braj'],
['bre','Breton'],
['btk','Batak languages'],
['bua','Buriat'],
['bug','Buginese'],
['bul','Bulgarian'],
['bur','Burmese'],
['byn','Blin; Bilin'],
['cad','Caddo'],
['cai','Central American Indian languages'],
['car','Galibi Carib'],
['cat','Catalan; Valencian'],
['cau','Caucasian languages'],
['ceb','Cebuano'],
['cel','Celtic languages'],
['cze','Czech'],
['cha','Chamorro'],
['chb','Chibcha'],
['che','Chechen'],
['chg','Chagatai'],
['chi','Chinese'],
['chk','Chuukese'],
['chm','Mari'],
['chn','Chinook jargon'],
['cho','Choctaw'],
['chp','Chipewyan; Dene Suline'],
['chr','Cherokee'],
['chu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'],
['chv','Chuvash'],
['chy','Cheyenne'],
['cmc','Chamic languages'],
['cop','Coptic'],
['cor','Cornish'],
['cos','Corsican'],
['cpe','Creoles and pidgins, English based'],
['cpf','Creoles and pidgins, French-based'],
['cpp','Creoles and pidgins, Portuguese-based'],
['cre','Cree'],
['crh','Crimean Tatar; Crimean Turkish'],
['crp','Creoles and pidgins'],
['csb','Kashubian'],
['cus','Cushitic languages'],
['wel','Welsh'],
['cze','Czech'],
['dak','Dakota'],
['dan','Danish'],
['dar','Dargwa'],
['day','Land Dayak languages'],
['del','Delaware'],
['den','Slave (Athapascan)'],
['ger','German'],
['dgr','Dogrib'],
['din','Dinka'],
['div','Divehi; Dhivehi; Maldivian'],
['doi','Dogri'],
['dra','Dravidian languages'],
['dsb','Lower Sorbian'],
['dua','Duala'],
['dum','Dutch, Middle (ca.1050-1350)'],
['dut','Dutch; Flemish'],
['dyu','Dyula'],
['dzo','Dzongkha'],
['efi','Efik'],
['egy','Egyptian (Ancient)'],
['eka','Ekajuk'],
['gre','Greek, Modern (1453-)'],
['elx','Elamite'],
['eng','English'],
['enm','English, Middle (1100-1500)'],
['epo','Esperanto'],
['est','Estonian'],
['baq','Basque'],
['ewe','Ewe'],
['ewo','Ewondo'],
['fan','Fang'],
['fao','Faroese'],
['per','Persian'],
['fat','Fanti'],
['fij','Fijian'],
['fil','Filipino; Pilipino'],
['fin','Finnish'],
['fiu','Finno-Ugrian languages'],
['fon','Fon'],
['fre','French'],
['fre','French'],
['frm','French, Middle (ca.1400-1600)'],
['fro','French, Old (842-ca.1400)'],
['frr','Northern Frisian'],
['frs','Eastern Frisian'],
['fry','Western Frisian'],
['ful','Fulah'],
['fur','Friulian'],
['gaa','Ga'],
['gay','Gayo'],
['gba','Gbaya'],
['gem','Germanic languages'],
['geo','Georgian'],
['ger','German'],
['gez','Geez'],
['gil','Gilbertese'],
['gla','Gaelic; Scottish Gaelic'],
['gle','Irish'],
['glg','Galician'],
['glv','Manx'],
['gmh','German, Middle High (ca.1050-1500)'],
['goh','German, Old High (ca.750-1050)'],
['gon','Gondi'],
['gor','Gorontalo'],
['got','Gothic'],
['grb','Grebo'],
['grc','Greek, Ancient (to 1453)'],
['gre','Greek, Modern (1453-)'],
['grn','Guarani'],
['gsw','Swiss German; Alemannic; Alsatian'],
['guj','Gujarati'],
['gwi','Gwich\'in'],
['hai','Haida'],
['hat','Haitian; Haitian Creole'],
['hau','Hausa'],
['haw','Hawaiian'],
['heb','Hebrew'],
['her','Herero'],
['hil','Hiligaynon'],
['him','Himachali languages; Western Pahari languages'],
['hin','Hindi'],
['hit','Hittite'],
['hmn','Hmong; Mong'],
['hmo','Hiri Motu'],
['hrv','Croatian'],
['hsb','Upper Sorbian'],
['hun','Hungarian'],
['hup','Hupa'],
['arm','Armenian'],
['iba','Iban'],
['ibo','Igbo'],
['ice','Icelandic'],
['ido','Ido'],
['iii','Sichuan Yi; Nuosu'],
['ijo','Ijo languages'],
['iku','Inuktitut'],
['ile','Interlingue; Occidental'],
['ilo','Iloko'],
['ina','Interlingua (International Auxiliary Language Association)'],
['inc','Indic languages'],
['ind','Indonesian'],
['ine','Indo-European languages'],
['inh','Ingush'],
['ipk','Inupiaq'],
['ira','Iranian languages'],
['iro','Iroquoian languages'],
['ice','Icelandic'],
['ita','Italian'],
['jav','Javanese'],
['jbo','Lojban'],
['jpn','Japanese'],
['jpr','Judeo-Persian'],
['jrb','Judeo-Arabic'],
['kaa','Kara-Kalpak'],
['kab','Kabyle'],
['kac','Kachin; Jingpho'],
['kal','Kalaallisut; Greenlandic'],
['kam','Kamba'],
['kan','Kannada'],
['kar','Karen languages'],
['kas','Kashmiri'],
['geo','Georgian'],
['kau','Kanuri'],
['kaw','Kawi'],
['kaz','Kazakh'],
['kbd','Kabardian'],
['kha','Khasi'],
['khi','Khoisan languages'],
['khm','Central Khmer'],
['kho','Khotanese; Sakan'],
['kik','Kikuyu; Gikuyu'],
['kin','Kinyarwanda'],
['kir','Kirghiz; Kyrgyz'],
['kmb','Kimbundu'],
['kok','Konkani'],
['kom','Komi'],
['kon','Kongo'],
['kor','Korean'],
['kos','Kosraean'],
['kpe','Kpelle'],
['krc','Karachay-Balkar'],
['krl','Karelian'],
['kro','Kru languages'],
['kru','Kurukh'],
['kua','Kuanyama; Kwanyama'],
['kum','Kumyk'],
['kur','Kurdish'],
['kut','Kutenai'],
['lad','Ladino'],
['lah','Lahnda'],
['lam','Lamba'],
['lao','Lao'],
['lat','Latin'],
['lav','Latvian'],
['lez','Lezghian'],
['lim','Limburgan; Limburger; Limburgish'],
['lin','Lingala'],
['lit','Lithuanian'],
['lol','Mongo'],
['loz','Lozi'],
['ltz','Luxembourgish; Letzeburgesch'],
['lua','Luba-Lulua'],
['lub','Luba-Katanga'],
['lug','Ganda'],
['lui','Luiseno'],
['lun','Lunda'],
['luo','Luo (Kenya and Tanzania)'],
['lus','Lushai'],
['mac','Macedonian'],
['mad','Madurese'],
['mag','Magahi'],
['mah','Marshallese'],
['mai','Maithili'],
['mak','Makasar'],
['mal','Malayalam'],
['man','Mandingo'],
['mao','Maori'],
['map','Austronesian languages'],
['mar','Marathi'],
['mas','Masai'],
['may','Malay'],
['mdf','Moksha'],
['mdr','Mandar'],
['men','Mende'],
['mga','Irish, Middle (900-1200)'],
['mic','Mi\'kmaq; Micmac'],
['min','Minangkabau'],
['mis','Uncoded languages'],
['mac','Macedonian'],
['mkh','Mon-Khmer languages'],
['mlg','Malagasy'],
['mlt','Maltese'],
['mnc','Manchu'],
['mni','Manipuri'],
['mno','Manobo languages'],
['moh','Mohawk'],
['mon','Mongolian'],
['mos','Mossi'],
['mao','Maori'],
['may','Malay'],
['mul','Multiple languages'],
['mun','Munda languages'],
['mus','Creek'],
['mwl','Mirandese'],
['mwr','Marwari'],
['bur','Burmese'],
['myn','Mayan languages'],
['myv','Erzya'],
['nah','Nahuatl languages'],
['nai','North American Indian languages'],
['nap','Neapolitan'],
['nau','Nauru'],
['nav','Navajo; Navaho'],
['nbl','Ndebele, South; South Ndebele'],
['nde','Ndebele, North; North Ndebele'],
['ndo','Ndonga'],
['nds','Low German; Low Saxon; German, Low; Saxon, Low'],
['nep','Nepali'],
['new','Nepal Bhasa; Newari'],
['nia','Nias'],
['nic','Niger-Kordofanian languages'],
['niu','Niuean'],
['dut','Dutch; Flemish'],
['nno','Norwegian Nynorsk; Nynorsk, Norwegian'],
['nob','Bokmål, Norwegian; Norwegian Bokmål'],
['nog','Nogai'],
['non','Norse, Old'],
['nor','Norwegian'],
['nqo','N\'Ko'],
['nso','Pedi; Sepedi; Northern Sotho'],
['nub','Nubian languages'],
['nwc','Classical Newari; Old Newari; Classical Nepal Bhasa'],
['nya','Chichewa; Chewa; Nyanja'],
['nym','Nyamwezi'],
['nyn','Nyankole'],
['nyo','Nyoro'],
['nzi','Nzima'],
['oci','Occitan (post 1500)'],
['oji','Ojibwa'],
['ori','Oriya'],
['orm','Oromo'],
['osa','Osage'],
['oss','Ossetian; Ossetic'],
['ota','Turkish, Ottoman (1500-1928)'],
['oto','Otomian languages'],
['paa','Papuan languages'],
['pag','Pangasinan'],
['pal','Pahlavi'],
['pam','Pampanga; Kapampangan'],
['pan','Panjabi; Punjabi'],
['pap','Papiamento'],
['pau','Palauan'],
['peo','Persian, Old (ca.600-400 B.C.)'],
['per','Persian'],
['phi','Philippine languages'],
['phn','Phoenician'],
['pli','Pali'],
['pol','Polish'],
['pon','Pohnpeian'],
['por','Portuguese'],
['pra','Prakrit languages'],
['pro','Provençal, Old (to 1500);Occitan, Old (to 1500)'],
['pus','Pushto; Pashto'],
['qaa','Reserved for local use'],
['que','Quechua'],
['raj','Rajasthani'],
['rap','Rapanui'],
['rar','Rarotongan; Cook Islands Maori'],
['roa','Romance languages'],
['roh','Romansh'],
['rom','Romany'],
['rum','Romanian; Moldavian; Moldovan'],
['rum','Romanian; Moldavian; Moldovan'],
['run','Rundi'],
['rup','Aromanian; Arumanian; Macedo-Romanian'],
['rus','Russian'],
['sad','Sandawe'],
['sag','Sango'],
['sah','Yakut'],
['sai','South American Indian languages'],
['sal','Salishan languages'],
['sam','Samaritan Aramaic'],
['san','Sanskrit'],
['sas','Sasak'],
['sat','Santali'],
['scn','Sicilian'],
['sco','Scots'],
['sel','Selkup'],
['sem','Semitic languages'],
['sga','Irish, Old (to 900)'],
['sgn','Sign Languages'],
['shn','Shan'],
['sid','Sidamo'],
['sin','Sinhala; Sinhalese'],
['sio','Siouan languages'],
['sit','Sino-Tibetan languages'],
['sla','Slavic languages'],
['slo','Slovak'],
['slo','Slovak'],
['slv','Slovenian'],
['sma','Southern Sami'],
['sme','Northern Sami'],
['smi','Sami languages'],
['smj','Lule Sami'],
['smn','Inari Sami'],
['smo','Samoan'],
['sms','Skolt Sami'],
['sna','Shona'],
['snd','Sindhi'],
['snk','Soninke'],
['sog','Sogdian'],
['som','Somali'],
['son','Songhai languages'],
['sot','Sotho, Southern'],
['spa','Spanish; Castilian'],
['alb','Albanian'],
['srd','Sardinian'],
['srn','Sranan Tongo'],
['srp','Serbian'],
['srr','Serer'],
['ssa','Nilo-Saharan languages'],
['ssw','Swati'],
['suk','Sukuma'],
['sun','Sundanese'],
['sus','Susu'],
['sux','Sumerian'],
['swa','Swahili'],
['swe','Swedish'],
['syc','Classical Syriac'],
['syr','Syriac'],
['tah','Tahitian'],
['tai','Tai languages'],
['tam','Tamil'],
['tat','Tatar'],
['tel','Telugu'],
['tem','Timne'],
['ter','Tereno'],
['tet','Tetum'],
['tgk','Tajik'],
['tgl','Tagalog'],
['tha','Thai'],
['tib','Tibetan'],
['tig','Tigre'],
['tir','Tigrinya'],
['tiv','Tiv'],
['tkl','Tokelau'],
['tlh','Klingon; tlhIngan-Hol'],
['tli','Tlingit'],
['tmh','Tamashek'],
['tog','Tonga (Nyasa)'],
['ton','Tonga (Tonga Islands)'],
['tpi','Tok Pisin'],
['tsi','Tsimshian'],
['tsn','Tswana'],
['tso','Tsonga'],
['tuk','Turkmen'],
['tum','Tumbuka'],
['tup','Tupi languages'],
['tur','Turkish'],
['tut','Altaic languages'],
['tvl','Tuvalu'],
['twi','Twi'],
['tyv','Tuvinian'],
['udm','Udmurt'],
['uga','Ugaritic'],
['uig','Uighur; Uyghur'],
['ukr','Ukrainian'],
['umb','Umbundu'],
['und','Undetermined'],
['urd','Urdu'],
['uzb','Uzbek'],
['vai','Vai'],
['ven','Venda'],
['vie','Vietnamese'],
['vol','Volapük'],
['vot','Votic'],
['wak','Wakashan languages'],
['wal','Wolaitta; Wolaytta'],
['war','Waray'],
['was','Washo'],
['wel','Welsh'],
['wen','Sorbian languages'],
['wln','Walloon'],
['wol','Wolof'],
['xal','Kalmyk; Oirat'],
['xho','Xhosa'],
['yao','Yao'],
['yap','Yapese'],
['yid','Yiddish'],
['yor','Yoruba'],
['ypk','Yupik languages'],
['zap','Zapotec'],
['zbl','Blissymbols; Blissymbolics; Bliss'],
['zen','Zenaga'],
['zgh','Standard Moroccan Tamazight'],
['zha','Zhuang; Chuang'],
['chi','Chinese'],
['znd','Zande languages'],
['zul','Zulu'],
['zun','Zuni'],
['zxx','No linguistic content; Not applicable'],
['zza','Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'],
]